{% set version = "22.9.24" %}

package:
  name: flatbuffers
  version: {{ version }}

source:
  url: https://github.com/google/flatbuffers/archive/v{{ version }}.tar.gz
  sha256: 40e0788873012def4d66a2fdbac15fbe012784473c01a703ccb5be33383556bf

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja

test:
  commands:
    - test -f $PREFIX/bin/flatc                                                     # [not win]
    - test -f $PREFIX/include/flatbuffers/flatbuffers.h                             # [not win]
    - test -f $PREFIX/lib/libflatbuffers${SHLIB_EXT}                                # [not win]
    - if not exist %PREFIX%\\Library\\bin\\flatc.exe exit 1                         # [win]
    - if not exist %PREFIX%\\Library\\include\\flatbuffers\\flatbuffers.h exit 1    # [win]

about:
  home: http://google.github.io/flatbuffers/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Memory Efficient Serialization Library

extra:
  recipe-maintainers:
    - wesm
    - msarahan
    - jakirkham
    - xhochy
