{% set version = "1.9.0" %}
{% set hash = "5ca5491e4260cacae30f1a5786d109230db3f3a6e5a0eb45d0d0608293d247e3" %}

package:
  name: flatbuffers
  version: {{ version }}

source:
  fn: flatbuffers-{{ version }}.tar.gz
  url: https://github.com/google/flatbuffers/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  skip: true  # [win and (py27 or py36)]
  
  features:
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - cmake
    - python  # [win]

test:
  requires:
    - python 3.4.*  # [win and py34]
    - python 3.5.*  # [win and py35]
  commands:
    - test -f $PREFIX/bin/flatc                                                     # [not win]
    - test -f $PREFIX/include/flatbuffers/flatbuffers.h                             # [not win]
    - if not exist %PREFIX%\\Library\\bin\\flatc.exe exit 1                         # [win]
    - if not exist %PREFIX%\\Library\\include\\flatbuffers\\flatbuffers.h exit 1    # [win]

about:
  home: http://google.github.io/flatbuffers/
  license: Apache 2.0
  summary: Memory Efficient Serialization Library

extra:
  recipe-maintainers:
    - wesm
    - msarahan
    - jakirkham
