{% set version = "23.1.4" %}

package:
  name: flatbuffers
  version: {{ version }}

source:
  url: https://github.com/google/flatbuffers/archive/v{{ version }}.tar.gz
  sha256: 801871ff3747838c0dd9730fc44ca9cc453ff42f9c8a0a2f1b33776d2ca5e4b9

build:
  number: 0
  run_exports:
    # SO version seems to track major version
    - {{ pin_subpackage('flatbuffers', max_pin='x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja

test:
  commands:
    - test -f $PREFIX/bin/flatc                                                     # [not win]
    - test -f $PREFIX/include/flatbuffers/flatbuffers.h                             # [not win]
    - test -f $PREFIX/lib/libflatbuffers${SHLIB_EXT}                                # [not win]
    - if not exist %PREFIX%\\Library\\bin\\flatc.exe exit 1                         # [win]
    - if not exist %PREFIX%\\Library\\include\\flatbuffers\\flatbuffers.h exit 1    # [win]

about:
  home: http://google.github.io/flatbuffers/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Memory Efficient Serialization Library

extra:
  recipe-maintainers:
    - wesm
    - msarahan
    - jakirkham
    - xhochy
