{% set version = "1.6.0" %}

package:
  name: flatbuffers
  version: {{ version }}

source:
  fn: flatbuffers-{{ version }}.tar.gz
  url: https://github.com/google/flatbuffers/archive/v{{ version }}.tar.gz
  sha256: 768c50ebf5823f8cde81a9e38ffff115c8f5a5d031a37520d0024e7b9c6cd22e

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - cmake

test:
  commands:
    - test -f $PREFIX/bin/flatc
    - test -f $PREFIX/include/flatbuffers/flatbuffers.h

about:
  home: http://google.github.io/flatbuffers/
  license: Apache License 2.0
  summary: Memory Efficient Serialization Library

extra:
  recipe-maintainers:
    - wesm
    - msarahan
    - jakirkham
